### ISSUE TITLE
Headphones audio distorted when plugged into the 3.5mm jack.

### ISSUE THREAD

**Issue by AxelDreemurr** [RobyRew/ASUS-FX504GE-Hackintosh_OpenCore#10]
Tried with the newer versions of AppleALC, tried different layout-ids but no luck. Can something be done regarding this?

**Comment by RobyRew** [comment]
> Tried with the newer versions of AppleALC, tried different layout-ids but no luck. Can something be done regarding this?

It’s a known bug, I have written a little on latest published Discussion :
https://github.com/RobyRew/ASUS-FX504GE-Hackintosh_OpenCore/discussions/9

Next week or so onSpain I have a few free-days so I can update some guides and search for solution.
I you want some recommendation for now I can give you

**Comment by AxelDreemurr** [comment]
Fixed for me when using alcid=30. HDMI broken as expected though.
