### ISSUE TITLE
SMBIOS problems

### ISSUE THREAD

**Issue by commet24** [RobyRew/ASUS-FX504GE-Hackintosh_OpenCore#11]
I successfully set up my SMBIOS, double-checked that in «Apple Check Your Coverage» website serial number isn't already in use.

But when setting up I can't get past «World Wide Technology Inc. can automatically set up your computer», because it needs credentials.

**Comment by RobyRew** [comment]
can you show a screenshot from that?

**Comment by RobyRew** [comment]
> I successfully set up my SMBIOS, double-checked that in «Apple Check Your Coverage» website serial number isn't already in use.
> 
> But when setting up I can't get past «World Wide Technology Inc. can automatically set up your computer», because it needs credentials.

Can you send a screenshot about that error, have you fixed or do you still have that error?
