### ISSUE TITLE
FX504GM HDMI No video output

### ISSUE THREAD

**Issue by ImAleeexx** [RobyRew/ASUS-FX504GE-Hackintosh_OpenCore#13]
Hey!

I'm trying to fix HDMI on my FX504GM and i don't get even the screen recognise the HDMI input.

Is your models HDMI port connected to the dGPU or iGPU?

**Comment by RobyRew** [comment]
This is my configuration on W11
![imagen](https://user-images.githubusercontent.com/49403384/160646627-ab115e77-10ac-42ab-aa0b-086ddb5b9128.png)
Can you show me what iGPU you have or IORegistry?

**Comment by ImAleeexx** [comment]
![image](https://user-images.githubusercontent.com/52298617/160683852-bf8e5ada-e9ef-453d-a207-64ae3f0f5509.png)
This is the config  that my laptop model has. It seems it cannot be possible to output video over HDMI as HDMI port is connected to dGPU directly

**Comment by RobyRew** [comment]
> This is the config that my laptop model has. It seems it cannot be possible to output video over HDMI as HDMI port is connected to dGPU directly

Have you changed any parameter of the Device Properties or any Boot Argument?
The SMBIOS of MacBookPro15,3 don't have HDMI and doesn't check for it, so it needs by force `agdpmod=vit9696` argument...
(now that I-m checking on Whatevergreen page they added a property for that too finally:
_or add `agdpmod` property to external GPU_)

I also want from you to try with Hackintool see if any external port or display is been shown wen connecting a display with HDMI.
![Screenshot 2022-03-30 at 18 21 26](https://user-images.githubusercontent.com/49403384/160883643-5515784a-91a5-4305-a013-03ef4e01920f.png)

**Comment by RobyRew** [comment]
> I see 0, 1, 2 ports on hackintool and when i connect a HDMI cable doesnt alter anything. I have `agdpmod=vit9696` boot arg correctly and i dont get even black screen on HDMI out

Have you found a fix for this?

**Comment by ImAleeexx** [comment]
Nope hehehe, i have desisted with the HDMI port

**Comment by ImAleeexx** [comment]
I have been looking out to solve this and i have arrived to this conclusion
The laptop that is made this guide for is a MUXless Optimus layout 1 system
The FX504GM Model is using the MUXless Optimus layout 2

The layout 1 has the HDMI port directly connected to the iGPU and communicates with dGPU via PCIe, but layout 2 has phisically connected the HDMI port to the dGPU and MacOS cannot even see the HDMI port as the dGPU is powered off via SSDT patch

![image](https://user-images.githubusercontent.com/52298617/162158057-5024706d-5ea7-42e8-bc8b-0d7fd06c30f1.png)

**Comment by RobyRew** [comment]
> I have been looking out to solve this and i have arrived to this conclusion
> 
> The laptop that is made this guide for is a MUXless Optimus layout 1 system
> 
> The FX504GM Model is using the MUXless Optimus layout 2
> 

It seems incredible to me that something so important varies from the GE or GM model.
 If you know for sure that it is a MUXless I am very sorry for you, what a bad luck :(, at least you will have good audio through the 3.5 jack.
Sorry for that. :(

**Comment by commet24** [comment]
ASUS FX504GD-DM151 Monterey - HDMI works with "NoHDMI-GoodAudio" config)
![16500122947466040597704762603161](https://user-images.githubusercontent.com/98208599/163548541-3f721f84-3501-4f2d-9831-23a8c5908dbb.jpg)

**Comment by RobyRew** [comment]
> ASUS FX504GD-DM151 Monterey - HDMI works with "NoHDMI-GoodAudio" config)

Maybe your model doesn't have my issue, or my monitor is not supported because 4k ultra wide format... (LG 38GN950)

**Comment by commet24** [comment]
> > ASUS FX504GD-DM151 Monterey - HDMI works with "NoHDMI-GoodAudio" config)
> 
> Maybe your model doesn't have my issue, or my monitor is not supported because 4k ultra wide format... (LG 38GN950)

 Maybe that. I don't have any 4K monitors, only 1080p.
