### ISSUE TITLE
Latest version of MacOS & OpenCore?

### ISSUE THREAD

**Issue by JustAHippo** [RobyRew/ASUS-FX504GE-Hackintosh_OpenCore#20]
I wanted to use this for Sonoma but I don't know whether it's up to date. If you could, is it possible if you were able to update the OpenCore version and maybe test Sonoma?

**Comment by JustAHippo** [comment]
Also can currently verify, Ventura installation is still working like a charm :)

**Comment by RobyRew** [comment]
@JustAHippo yoooo man, try now to see how its working for you, everything is updated to the last version

**Comment by RobyRew** [comment]
im running Sonoma with latest OC 0.9.7 running smoothly
